### ISSUE TITLE
Compilation error with Wireshark SVN repo

### ISSUE THREAD

**Issue by xplico** [davidgfnet/wireshark-whatsapp#10]
Hi,
there are some errors if we compile this code using Wireshark dev repository.
To solve them, add as first parameter to the tvb_memdup function (line 62 and 78 of packet-whatsapp.c) NULL.

Ciao.
Gianluca

**Comment by davidgfnet** [comment]
This is fixed now! I just could reproduce the error due to my wireshark being updated.
