### ISSUE TITLE
How to download the headers?

### ISSUE THREAD

**Issue by sabatesduran** [davidgfnet/wireshark-whatsapp#11]
How can install the headers in the description?
-wireshark headers
-glib-2.0 headers
-libcrypto headers (install openssl headers)

I have Ubuntu 13.04.

The error when I do cmake .. are this:

-- The C compiler identification is GNU 4.7.3
-- The CXX compiler identification is GNU 4.7.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for one of the modules 'glib-2.0>=2.4.0'
CMake Error at cmake/FindWireshark.cmake:26 (MESSAGE):
  Could NOT find the wireshark library and headers
Call Stack (most recent call first):
  CMakeLists.txt:48 (find_package)

-- Wireshark libs not found!
-- Found libcrypto: /usr/lib/x86_64-linux-gnu/libcrypto.so
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WIRESHARK_INCLUDE_DIRS
   used as include directory in directory /home/didac/Desktop/wireshark-whatsapp-master

-- Configuring incomplete, errors occurred!

**Comment by sahilshekhawat** [comment]
I got the same error, it will be nice if this can be mentioned in Readme.

**Comment by sahilshekhawat** [comment]
And also, how to set ``WIRESHARK_INCLUDE_DIRS`` in linux?
