### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by ChrisPooh** [davidgfnet/wireshark-whatsapp#20]
parallels@ubuntu:~/wireshark-whatsapp-master$ sudo apt-get install wireshark-dev libglib2.0-dev libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
wireshark-dev is already the newest version.
libglib2.0-dev is already the newest version.
libssl-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 311 not upgraded.
parallels@ubuntu:~/wireshark-whatsapp-master$ cmake .
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WIRESHARK_INCLUDE_DIRS
   used as include directory in directory /home/parallels/wireshark-whatsapp-master

-- Configuring incomplete, errors occurred!
See also "/home/parallels/wireshark-whatsapp-master/CMakeFiles/CMakeOutput.log".
See also "/home/parallels/wireshark-whatsapp-master/CMakeFiles/CMakeError.log".
parallels@ubuntu:~/wireshark-whatsapp-master$ 

Hi there, could you advise what i am missing from the above?

**Comment by davidgfnet** [comment]
You are probably using an old version of wireshark. Commit 4ea1795645660a738c51bb8b3693ff221e339233 updated to latest version. Check your version and maybe try removing that commit

**Comment by ChrisPooh** [comment]
Hi david, appreciate your prompt response! anyway, I have verified my wireshark version and tested against different commits (including latest). Do I have to hardcode the path of the wireshark lib?

parallels@ubuntu:~$ wireshark -v
wireshark 1.12.3 (v1.12.3-0-gbb3e9a0 from master-1.12)

Copyright 1998-2015 Gerald Combs <gerald@wireshark.org> and contributors.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with GTK+ 3.10.8, with Cairo 1.13.1, with Pango 1.36.3, with
GLib 2.40.2, with libpcap, with libz 1.2.8, with POSIX capabilities (Linux),
with libnl 3, with SMI 0.4.8, with c-ares 1.10.0, with Lua 5.2, without Python,
with GnuTLS 3.2.11, with Gcrypt 1.5.3, with MIT Kerberos, with GeoIP, with
PortAudio V19-devel (built Feb 25 2014 21:09:53), without AirPcap.

Running on Linux 3.13.0-34-generic, with locale en_US.UTF-8, with libpcap
version 1.5.3, with libz 1.2.8, GnuTLS 3.2.11, Gcrypt 1.5.3.
Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz

Built using gcc 4.8.2.
parallels@ubuntu:~$ cd wireshark-whatsapp-master/
parallels@ubuntu:~/wireshark-whatsapp-master$ mkdir build
parallels@ubuntu:~/wireshark-whatsapp-master$ cd build
parallels@ubuntu:~/wireshark-whatsapp-master/build$ cmake ..
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for one of the modules 'glib-2.0>=2.4.0'
-- Found GLib2: glib-2.0 /usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include
-- Looking for include file glib/gregex.h
-- Looking for include file glib/gregex.h - not found
-- Looking for include file glib/gchecksum.h
-- Looking for include file glib/gchecksum.h - not found
CMake Error at cmake/FindWireshark.cmake:26 (MESSAGE):
  Could NOT find the wireshark library and headers
Call Stack (most recent call first):
  CMakeLists.txt:48 (find_package)


-- Wireshark libs not found!
-- Found libcrypto: /usr/lib/x86_64-linux-gnu/libcrypto.so
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WIRESHARK_INCLUDE_DIRS
   used as include directory in directory /home/parallels/wireshark-whatsapp-master

-- Configuring incomplete, errors occurred!
See also "/home/parallels/wireshark-whatsapp-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/parallels/wireshark-whatsapp-master/build/CMakeFiles/CMakeError.log".
parallels@ubuntu:~/wireshark-whatsapp-master/build$

**Comment by davidgfnet** [comment]
Hold on, have you installed wireshark headers (the packages wireshark-dev or similar)?

**Comment by ChrisPooh** [comment]
Yes, thanks for the remainder. I remove my old wireshark version and reinstall the updated version. 
Just one step closer. I really appreciated your help. thumbs up. 

parallels@ubuntu:~$ cd wireshark-whatsapp-master/
parallels@ubuntu:~/wireshark-whatsapp-master$ ls
AUTHORS         debian             protocol-spec.txt  whatsapp-proto.cc
ChangeLog       INSTALL            README             whatsapp-proto.h
cmake           moduleinfo.h       README.md
CMakeLists.txt  NEWS               tinfl.c
COPYING         packet-whatsapp.c  tools
parallels@ubuntu:~/wireshark-whatsapp-master$ mkdir build
parallels@ubuntu:~/wireshark-whatsapp-master$ 
parallels@ubuntu:~/wireshark-whatsapp-master$ cd build
parallels@ubuntu:~/wireshark-whatsapp-master/build$ cmake ..
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for one of the modules 'glib-2.0>=2.4.0'
-- Found GLib2: glib-2.0 /usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include
-- Looking for include file glib/gregex.h
-- Looking for include file glib/gregex.h - not found
-- Looking for include file glib/gchecksum.h
-- Looking for include file glib/gchecksum.h - not found
-- Found wireshark libs at /usr/include/wireshark
-- Found libcrypto: /usr/lib/x86_64-linux-gnu/libcrypto.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/parallels/wireshark-whatsapp-master/build
parallels@ubuntu:~/wireshark-whatsapp-master/build$ make
[ 20%] Generating plugin.c
Scanning dependencies of target whatsapp
[ 40%] Building C object CMakeFiles/whatsapp.dir/plugin.c.o
[ 60%] Building C object CMakeFiles/whatsapp.dir/packet-whatsapp.c.o
In file included from /usr/include/wireshark/epan/proto.h:46:0,
                 from /usr/include/wireshark/epan/packet.h:26,
                 from /home/parallels/wireshark-whatsapp-master/packet-whatsapp.c:11:
/usr/include/wireshark/epan/emem.h:29:30: fatal error: ws_symbol_export.h: No such file or directory
 #include "ws_symbol_export.h"
                              ^
compilation terminated.
make[2]: *** [CMakeFiles/whatsapp.dir/packet-whatsapp.c.o] Error 1
make[1]: *** [CMakeFiles/whatsapp.dir/all] Error 2
make: *** [all] Error 2
parallels@ubuntu:~/wireshark-whatsapp-master/build$

**Comment by davidgfnet** [comment]
Google it. It seems your wireshark installation is fucked up. It has nothing to do with this plugin.

**Comment by ChrisPooh** [comment]
No worries:) Keep up the good work.
