### ISSUE TITLE
New Protocol Whatsapp 1.X that caused break to either wa_proxy and wiresharkwa

### ISSUE THREAD

**Issue by assegaf** [davidgfnet/wireshark-whatsapp#27]
@davidgfnet  any idea about the new protocol of android 2.12.3x, seem wiresharkwa and wa_proxy cant handle.
the new protocol stream usually is WA15, now is WA16 ..

**Comment by SebastianA** [comment]
i have the same problem. the yowsup client is able to handle that...

**Comment by assegaf** [comment]
seem @davidgfnet  already impletented the wireshark whatsapp v1.6, hopefully he commented something
