### ISSUE TITLE
Still working with last android client encryption ?

### ISSUE THREAD

**Issue by assegaf** [davidgfnet/wireshark-whatsapp#5]
@davidgfnet 

hi david, I have tried to see whats happen rx and tx.
( we know its using port 5222), but only at first (sending number and password) and its reply works. after that, everything else still encrypted,

is it still working ? or whatsapp using new encryption method ?

**Comment by assegaf** [comment]
@davidgfnet 
hi david, seem I ever ask about this and I redoing again I forgot that almost a year ago .. and stuck again,
after send WAUTH and challenges bytes, then its not decrypt all again,

I assume the challenges key is send via android client not created from start, so What do I do to make android send the new challenges from start ?

**Comment by assegaf** [comment]
@davidgfnet 

tested, and indeed new registration first Auth didnot send challenges blob key,
and got it challenge blob on reply, and then send [response] node, then after it all is encrypted again .. not single node Unencrypted after it ...

any idea ?



this is the log ..

TX
[auth user=62XXXXXXX passive=true mechanism=WAUTH-2>]
[/auth]

--------------------------------------
RX
from : s.whatsapp.net
[stream:features]
[/stream:features]
[challenge]
 BLOB
[/challenge]


TX
[response]
blob : \x7fB\xffdV\x04\x15\xc2\xc5E)\x09\xa6\x08\xb1\x0f\x93g6\xf5\xd3\x91\x8ft\x81J\xd4*\xc1_x\xaaE\xcfh\x0b\xd0\xb2\x8e.x\xb6\xe4\xc9\xf3\x85\xd4\xbf\x14\x1e\xdf\xf9\x1fd\x9a?;\x0a\x03T2JV+5#4\xdc\xed<\x7f\xd3\xb7p\xc3v\xdb|\xe0\xd7\xbbP/\xc99\xab\x12\xa6\xd1_ \xad\"\x09\x99G\xed\x07\xee\xf1\x16J|C\x95\xf0
</response>

HMAC-SHA1: 0x7f42ff64 (calculated: 0xb3357bfa) (session key: Out key: f7d9a1e8 a174b701 9e4e4e4f da9dcc01 ff253922 Out HMAC: 64bccb51 d41193e3 6ea69f17 1226741b 9acf7865 In key: df34cf2d 42b1cc44 053d3e3b b8470e93 8db3f654 In HMAC: 37151f0
Crypted message

**Comment by davidgfnet** [comment]
Wrong password?

**Comment by assegaf** [comment]
yeah I think so, but thats happening, I am thinking about version of android/client User Agent,
may I know what you use ?

**Comment by davidgfnet** [comment]
I'm using the latest whatsapp on my phone, I recall it being 2.12.5.

**Comment by assegaf** [comment]
@davidgfnet 
you are right, new client working fine, but I think because password wrong previously. now I can see all unecnrypted only after registration new.

is there any way to force whatsapp to use full handshake ?
I tried to force stop, clear cache on android apps menu, seem still using saved handshake. not sure where it came from,

also my android is rooted, in case need deleting files.

**Comment by davidgfnet** [comment]
I have no idea, that's why I use the tool I created last week: to strip the saved blob which triggers the fast handshake.

**Comment by assegaf** [comment]
ok thanks for all your hard work,
I am finding it now inside rooted android, somewhere on data I suppose, currently someone already has known already where to save password. so might be same place,

Update:
with your tool you created last week, its working, and I can get unencrypted again
well at least with modif (because seem my blob < 8*16) :

       printf("Got AUTH request from client with count %d!\n", count);
	if (count < 7*16) return -1; // Would have a big blob of data


you save my day :)

**Comment by assegaf** [comment]
Closed, Everything is Fixed, new feature and handshake etc...,

**Comment by assegaf** [comment]
@davidgfnet 
you already provide everything, trace, source (purple), even the working sample of plugin pidgin.
but I tried to rewrite using c#, but got

[success t="" action="cancel" digest="not-authorized" show="list" props="4" kind="free"]BLOBxxxx[/success]

this is kinda new, success Login but not like usually, and everything else not working after that. maybe when you develop it found similar problem ?

tried with pidgin-wa, working.

Tag: success
at[creation]=1423750035
at[expiration]=1455286035
at[kind]=free
at[props]=4
at[status]=active
at[t]=1426641228
Data: 'blb

**Comment by assegaf** [comment]
Thanks I follow you code in wa purple to read nibble encoding, and working fine now.
and I follow your idea not to use nibble encoding when doing TX , 
so far on TX nibble encoding, when String of Number is Odd , just add F as end of string.
example: 601234567
to be 601234567F

(length is 5)


but maybe need more idea, example Nibble encoding of Number with dash '-' to send message id, example :

14167162712-1

no idea how to encode it ?
